RoR/config/routes.rb
Rails.application.routes.draw do
  resources :notes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RoR/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RoR/app/models/note.rb
class Note < ApplicationRecord

end

RoR/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

RoR/app/controllers/notes_controller.rb
class NotesController < ApplicationController

    def index
        @notes = Note.all
    end

    def new
        @note = Note.new
    end

    def create
        @note = Note.new(note_params)
        @note.save

        redirect_to notes_path

    end

    def show 
        @note = Note.find(params[:id])
    end        

    def edit
        @note = Note.find(params[:id])
    end

    def update
        @note = Note.find(params[:id])
        @note.update(note_params)

        redirect_to notes_path
    end

    def destroy
        @note = Note.find(params[:id])
        @note.destroy
        redirect_to notes_path
    end

    def note_params
        params.require(:note).permit(:name, :content)
    end

end

RoR/app/helpers/application_helper.rb
module ApplicationHelper
end

RoR/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warsztat3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

RoR/app/views/notes/edit.html.haml
= form_with model: @note, local: true do |form|
    %p
        = form.label :Name
        = form.text_field :name
    %p
        = form.label :Content
        = form.text_area :content
    =form.submit

RoR/app/views/notes/index.html.haml
- @notes.each do |note| 
    %p
        = note.name
        = note.content
    %p
        = link_to "Edit", edit_note_path(note)
        = link_to "Destroy", note_path(note), method: :Delete
        = link_to "Show", note_path(note)
    %p 
        =link_to "New note", new_note_path

RoR/app/views/notes/new.html.haml
= form_with model: @note, local: true do |form|
    %p 
        = form.label :Name
        = form.text_field :name
    %p
        = form.label :Content
        = form.text_area :content
    =form.submit

RoR/app/views/notes/show.html.haml
%p 
    Name:
    =@note.name 
%p
    Content:
    =@note.content    
%p
    =link_to "Index", notes_path
    =link_to "Edit note", edit_note_path(@note)
    =link_to "Delete", note_path(@note), method: :delete